/**
 * Display — SUPERSEDED. Do not edit this file.
 *
 * There are two TV screens in this codebase and this is the old one. The
 * live screen is `TvDisplay.jsx` at `/display/:slug`, which is what Display
 * Setup generates a link and QR code for, and therefore what is actually on
 * the wall. Nothing links to `/display-tv/:branchId` any more.
 *
 * On 5 September a batch of work — alert and pause banners, a waiting count,
 * generated staff colours, showing only the counters that exist — was added
 * here by mistake and had no effect on anything. TvDisplay already had the
 * banners and the count.
 *
 * Left in place rather than deleted because the route still resolves and
 * somebody may have bookmarked it on a device in the office. Delete once
 * that is confirmed. Any change intended for the waiting room belongs in
 * TvDisplay.jsx.
 */

import { useEffect, useRef, useState } from "react";
import { useParams } from "react-router-dom";
import { supabase } from "../lib/supabase";
import { loadActiveAlert } from "../lib/alerts";
import { useDisplay } from "../hooks/useDisplay";

const PALETTE = ["#c9a86a", "#74b9e8", "#9bbd9b", "#d49185", "#b8a2d4", "#e0b070"];

function staffColor(staffId) {
  if (!staffId) return "#6e6c65";
  let h = 0;
  for (let i = 0; i < staffId.length; i++) h = (h * 31 + staffId.charCodeAt(i)) >>> 0;
  return PALETTE[h % PALETTE.length];
}

export default function Display() {
  const { branchId } = useParams();
  const { branchName, serving, waiting, staff, stations, loading } = useDisplay();

  /* ── Banners ──────────────────────────────────────────────────
     Two things the room needs to be told and currently is not: a message
     staff posted, and whether the queue is paused. Both already exist and
     were only ever shown on the staff screen — which is the one screen the
     people waiting cannot see. Polled rather than subscribed because a TV
     is left running for hours and a dropped socket would silently freeze
     the banner. */
  const [alert, setAlert] = useState(null);
  const [pausedAt, setPausedAt] = useState(null);

  useEffect(() => {
    if (!branchId) return;
    let off = false;
    const check = async () => {
      const [a, { data: b }] = await Promise.all([
        loadActiveAlert(branchId).catch(() => null),
        supabase.from("branches").select("queue_paused_at").eq("id", branchId).maybeSingle(),
      ]);
      if (off) return;
      setAlert(a);
      setPausedAt(b?.queue_paused_at ?? null);
    };
    check();
    const id = setInterval(check, 20_000);
    return () => { off = true; clearInterval(id); };
  }, [branchId]);

  /* ── Live clock ─────────────────────────────────────────────── */
  const [now, setNow] = useState(new Date());
  useEffect(() => {
    const id = setInterval(() => setNow(new Date()), 1000);
    return () => clearInterval(id);
  }, []);

  const timeStr = now.toLocaleTimeString([], {
    hour:   "2-digit",
    minute: "2-digit",
    second: "2-digit",
    hour12: true,
  });

  /* ── Flash animation when a ticket is called (C5) ──────────── */
  const [flashingId, setFlashingId] = useState(null);
  const prevCalledAt = useRef({});

  useEffect(() => {
    serving.forEach((t) => {
      const prev = prevCalledAt.current[t.id];
      if (t.called_at && t.called_at !== prev) {
        setFlashingId(t.id);
        setTimeout(
          () => setFlashingId((cur) => (cur === t.id ? null : cur)),
          3000
        );
      }
      prevCalledAt.current[t.id] = t.called_at;
    });
  }, [serving]);

  /* ── Fullscreen toggle ──────────────────────────────────────── */
  function toggleFullscreen() {
    if (!document.fullscreenElement) {
      document.documentElement.requestFullscreen().catch(() => {});
    } else {
      document.exitFullscreen().catch(() => {});
    }
  }

  /* ── Build lookup maps ──────────────────────────────────────── */
  // staffId → staff row
  const staffById = {};
  staff.forEach((s) => { staffById[s.id] = s; });

  // stationId → serving ticket
  const servingByStation = {};
  serving.forEach((t) => {
    if (t.assigned_station_id) servingByStation[t.assigned_station_id] = t;
  });

  /* ── Station cards ──────────────────────────────────────────── */
  // Always show 4 cards. If DB has fewer stations, pad with placeholder cards.
  /* Show the counters that exist, not always four. Padding to four meant a
     two-counter office displayed two empty boxes on the waiting-room wall
     for the whole day, which reads as "two counters closed" rather than
     "this office has two counters". */
  const WINDOW_LABELS = stations.length
    ? stations.map((st) => st.window_number).filter((n) => n != null).sort((a, b) => a - b)
    : [1];
  const stationCards = WINDOW_LABELS.map((winNum) => {
    const station = stations.find((s) => s.window_number === winNum) ?? null;
    const ticket  = station ? servingByStation[station.id] ?? null : null;
    const staffMember = station?.staff_id ? staffById[station.staff_id] ?? null : null;

    // Also check if any serving ticket is assigned to a staff at this window
    // (fallback for when assigned_station_id isn't set)
    const fallbackTicket = !ticket
      ? serving.find((t) => staffMember && t.staff_id === staffMember.id) ?? null
      : null;

    const activeTicket = ticket ?? fallbackTicket;
    const color = staffMember ? staffColor(staffMember.id) : "#6e6c65";

    return { winNum, station, staffMember, ticket: activeTicket, color };
  });

  /* ── Loading screen ─────────────────────────────────────────── */
  if (loading) {
    return (
      <div
        className="min-h-screen flex items-center justify-center"
        style={{ background: "#0b0b0c" }}
      >
        <div
          className="font-display font-light"
          style={{ color: "#c9a86a", fontSize: 48, opacity: 0.4 }}
        >
          AzQueue
        </div>
      </div>
    );
  }

  return (
    <div
      className="min-h-screen flex flex-col select-none overflow-hidden"
      style={{ background: "#0b0b0c", color: "#f2f0ea" }}
    >
      <style>{`
        @keyframes azq-flash {
          0%   { box-shadow: 0 0 0px rgba(201,168,106,0); }
          20%  { box-shadow: 0 0 60px rgba(201,168,106,0.65); }
          60%  { box-shadow: 0 0 40px rgba(201,168,106,0.45); }
          100% { box-shadow: 0 0 0px rgba(201,168,106,0); }
        }
        @keyframes azq-name-flash {
          0%,100% { color: #f2f0ea; }
          20%,40% { color: #c9a86a; text-shadow: 0 0 18px rgba(201,168,106,0.9); }
        }
        .azq-card-flash  { animation: azq-flash      3s ease-out forwards; }
        .azq-name-flash  { animation: azq-name-flash 3s ease-out forwards; }
      `}</style>
      {/* ── Top bar ─────────────────────────────────────────── */}
      <header
        className="flex items-center justify-between px-10 shrink-0"
        style={{
          height: 80,
          borderBottom: "1px solid #26262a",
          background: "rgba(11,11,12,0.95)",
        }}
      >
        {/* Left: logo + branch name */}
        <div className="flex items-center gap-4">
          <div
            className="flex items-center justify-center rounded-sm"
            style={{
              width: 40,
              height: 40,
              background: "#c9a86a",
              boxShadow: "0 0 28px rgba(201,168,106,0.35)",
            }}
          >
            <span
              className="font-display font-semibold"
              style={{ color: "#141410", fontSize: 14 }}
            >
              AQ
            </span>
          </div>
          <span
            className="font-display font-light tracking-tight"
            style={{ color: "#e4cb95", fontSize: 28 }}
          >
            {branchName || "AzQueue"}
          </span>
        </div>

        {/* Right: live clock */}
        <div
          style={{
            fontFamily: "'JetBrains Mono', monospace",
            fontSize: 24,
            color: "#a8a69e",
            letterSpacing: "0.04em",
          }}
        >
          {timeStr}
        </div>
      </header>

      {/* ── Banners ─────────────────────────────────────────────
          Paused takes priority over a posted message: if the queue is not
          moving, that is the single most useful sentence on the screen and
          nothing should sit above it. */}
      {pausedAt ? (
        <div
          className="px-10 py-5 shrink-0 flex items-center gap-4"
          style={{ background: "rgba(164,97,79,0.18)", borderBottom: "1px solid rgba(164,97,79,0.5)" }}
        >
          <span
            style={{ width: 10, height: 10, borderRadius: "50%", background: "#d49185", flexShrink: 0 }}
          />
          <span style={{ fontFamily: "Inter, sans-serif", fontSize: 22, color: "#f0c9bf" }}>
            We have paused briefly — you keep your place in the queue.
          </span>
        </div>
      ) : alert ? (
        <div
          className="px-10 py-5 shrink-0 flex items-center gap-4"
          style={{ background: "rgba(201,168,106,0.12)", borderBottom: "1px solid rgba(201,168,106,0.4)" }}
        >
          <span
            style={{ width: 10, height: 10, borderRadius: "50%", background: "#c9a86a", flexShrink: 0 }}
          />
          <span style={{ fontFamily: "Inter, sans-serif", fontSize: 22, color: "#e4cb95" }}>
            {alert.message}
          </span>
        </div>
      ) : null}

      {/* ── Main area ───────────────────────────────────────── */}
      <main className="flex-1 flex flex-col px-10 py-8">
        {/* Section label */}
        <div
          className="text-center mb-8"
          style={{
            fontFamily: "Inter, sans-serif",
            fontSize: 11,
            letterSpacing: "0.28em",
            textTransform: "uppercase",
            color: "#6e6c65",
          }}
        >
          Now Serving
        </div>

        {/* 4 station cards */}
        <div
          className="grid gap-5 flex-1"
          style={{
            gridTemplateColumns: `repeat(${Math.min(WINDOW_LABELS.length, 4)}, 1fr)`,
            maxHeight: "calc(100vh - 280px)",
          }}
        >
          {stationCards.map(({ winNum, station, staffMember, ticket, color }) => {
            const isServing = !!ticket;
            const isFlashing = !!ticket && flashingId === ticket.id;
            return (
              <div
                key={winNum}
                className={`flex flex-col p-8 transition-all duration-700${isFlashing ? " azq-card-flash" : ""}`}
                style={{
                  border: isServing
                    ? `2px solid ${color}44`
                    : "1px solid #26262a",
                  background: isServing
                    ? `linear-gradient(160deg, ${color}08 0%, transparent 60%)`
                    : "transparent",
                  borderRadius: 2,
                }}
              >
                {/* Window + staff name */}
                <div
                  className="mb-6"
                  style={{
                    fontFamily: "Inter, sans-serif",
                    fontSize: 11,
                    letterSpacing: "0.22em",
                    textTransform: "uppercase",
                    color: isServing ? color : "#6e6c65",
                  }}
                >
                  Window {winNum}
                  {staffMember && (
                    <span style={{ color: isServing ? color : "#6e6c65" }}>
                      {" "}· {staffMember.display_name}
                    </span>
                  )}
                </div>

                {/* Token — dominant element */}
                <div
                  className="font-display font-light leading-none flex-1 flex items-center"
                  style={{
                    fontSize: 120,
                    color: isServing ? color : "#26262a",
                    transition: "color 0.5s ease",
                  }}
                >
                  {ticket?.token ?? "—"}
                </div>

                {/* Customer name / Available */}
                <div
                  className={`mt-4${isFlashing ? " azq-name-flash" : ""}`}
                  style={{
                    fontSize: 18,
                    color: isServing ? "#f2f0ea" : "#3a3a3f",
                    fontFamily: "Inter, sans-serif",
                    fontWeight: 400,
                  }}
                >
                  {isServing ? (ticket.customer_name || "Guest") : "Available"}
                </div>

                {/* Service name */}
                {isServing && ticket.service_id && (
                  <div
                    className="mt-1"
                    style={{
                      fontSize: 12,
                      color: "#6e6c65",
                      fontFamily: "Inter, sans-serif",
                    }}
                  >
                    {/* service_id shown; a future join could show name */}
                    In service
                  </div>
                )}
              </div>
            );
          })}
        </div>
      </main>

      {/* ── Bottom strip: Up Next ───────────────────────────── */}
      <footer
        style={{
          borderTop: "1px solid #26262a",
          padding: "20px 40px",
          background: "rgba(11,11,12,0.97)",
        }}
      >
        {/* HOW MANY ARE AHEAD, NOT HOW LONG IT WILL TAKE.
            A minute estimate is the thing everyone asks for and the thing
            this screen cannot yet say honestly — per-counter timings need
            several completed visits each before they mean anything, and the
            owner handles the long cases, so a single office-wide average
            would be wrong for exactly the people waiting longest.

            A count is always true, needs no history, and answers most of
            what someone actually wants to know. The timings can join this
            later, per counter, once they are measured. */}
        <div
          className="mb-4 flex items-baseline gap-3"
          style={{ fontFamily: "Inter, sans-serif" }}
        >
          <span
            style={{
              fontSize: 11,
              letterSpacing: "0.28em",
              textTransform: "uppercase",
              color: "#6e6c65",
            }}
          >
            Up Next
          </span>
          {waiting.length > 0 && (
            <span style={{ fontSize: 13, color: "#8a8880" }}>
              {waiting.length} {waiting.length === 1 ? "person waiting" : "people waiting"}
            </span>
          )}
        </div>

        {waiting.length === 0 ? (
          <div
            style={{
              fontFamily: "Inter, sans-serif",
              fontSize: 16,
              color: "#3a3a3f",
            }}
          >
            Queue is clear
          </div>
        ) : (
          <div className="flex items-center gap-6">
            {waiting.slice(0, 6).map((t, i) => {
              const firstName = t.customer_name?.split(" ")[0] ?? "";
              return (
                <div
                  key={t.id}
                  className="flex flex-col items-center"
                  style={{
                    opacity: 1 - i * 0.12,
                  }}
                >
                  <span
                    className="font-display font-light"
                    style={{ fontSize: 28, color: "#c9a86a", lineHeight: 1 }}
                  >
                    {t.token}
                  </span>
                  <span
                    style={{
                      fontSize: 11,
                      color: "#6e6c65",
                      marginTop: 4,
                      fontFamily: "Inter, sans-serif",
                    }}
                  >
                    {firstName}
                  </span>
                </div>
              );
            })}

            {waiting.length > 6 && (
              <div
                style={{
                  fontSize: 12,
                  color: "#3a3a3f",
                  fontFamily: "Inter, sans-serif",
                  marginLeft: 8,
                }}
              >
                +{waiting.length - 6} more
              </div>
            )}
          </div>
        )}
      </footer>

      {/* ── Fullscreen button ───────────────────────────────── */}
      <button
        onClick={toggleFullscreen}
        style={{
          position: "fixed",
          bottom: 16,
          right: 20,
          background: "transparent",
          border: "1px solid #26262a",
          color: "#3a3a3f",
          fontSize: 11,
          fontFamily: "Inter, sans-serif",
          letterSpacing: "0.1em",
          padding: "6px 10px",
          cursor: "pointer",
          transition: "color 0.2s, border-color 0.2s",
          zIndex: 50,
        }}
        onMouseEnter={(e) => {
          e.currentTarget.style.color = "#a8a69e";
          e.currentTarget.style.borderColor = "#3a3a3f";
        }}
        onMouseLeave={(e) => {
          e.currentTarget.style.color = "#3a3a3f";
          e.currentTarget.style.borderColor = "#26262a";
        }}
      >
        ⛶ Fullscreen
      </button>
    </div>
  );
}
