/**
 * shopify.js — Shopify Admin API integration for AzQueue.
 *
 * Uses a Custom App access token (generated by the store owner himself in
 * Shopify Admin → Settings → Apps and sales channels → Develop apps →
 * Create an app → Admin API access token) instead of a full OAuth flow.
 * That's the right tradeoff for connecting ONE specific store: no Shopify
 * Partner account needed, no server-side client secret to manage — just a
 * token the owner pastes in. Same shape as the Freshdesk integration.
 *
 * (Full OAuth — see zid.js for what that looks like — only pays off if
 * AzQueue itself becomes a public Shopify App many different merchants
 * install. Not the case here: one client, one store, his own token.)
 *
 * HOW TO GET YOUR ACCESS TOKEN:
 *   1. Log in to your Shopify Admin (yourstore.myshopify.com/admin)
 *   2. Settings → Apps and sales channels → Develop apps
 *   3. "Create an app" → under Configuration, grant Admin API scopes:
 *      read_customers, read_orders, read_products (read-only is enough)
 *   4. Install the app → reveal the Admin API access token (starts "shpat_")
 *   5. Copy it, plus your shop domain (yourstore.myshopify.com), into
 *      AzQueue Settings → Integrations → Shopify
 *
 * The token + shop domain are stored in channel_connections (channel =
 * 'shopify'), visible only to the branch owner — same RLS as Freshdesk/Zid.
 */

import { supabase } from "./supabase";

// Bump periodically — Shopify retires API versions roughly a year after release.
const API_VERSION = "2024-10";

function cleanDomain(shopDomain) {
  return shopDomain.trim().replace(/^https?:\/\//, "").replace(/\/+$/, "");
}

function adminUrl(shopDomain, path) {
  return `https://${cleanDomain(shopDomain)}/admin/api/${API_VERSION}${path}`;
}

function shopifyHeaders(accessToken) {
  return { "X-Shopify-Access-Token": accessToken, "Content-Type": "application/json" };
}

// ── Config helpers ────────────────────────────────────────────────────────

/**
 * Load the Shopify credentials for a branch.
 * Returns { accessToken, shopDomain } or null if not configured.
 */
export async function getShopifyConfig(branchId) {
  const { data } = await supabase
    .from("channel_connections")
    .select("config, status")
    .eq("branch_id", branchId)
    .eq("channel", "shopify")
    .maybeSingle();

  if (!data?.config?.accessToken || !data?.config?.shopDomain) return null;
  return { accessToken: data.config.accessToken, shopDomain: data.config.shopDomain };
}

/**
 * Save Shopify credentials for a branch.
 * Tests the connection before saving — throws if invalid.
 */
export async function saveShopifyConfig(branchId, { accessToken, shopDomain }) {
  const domain = cleanDomain(shopDomain);
  const testOk = await testShopifyCredentials(accessToken, domain);
  if (!testOk) throw new Error("Invalid access token or shop domain — please check and try again.");

  const { error } = await supabase
    .from("channel_connections")
    .upsert(
      {
        branch_id: branchId,
        channel: "shopify",
        status: "connected",
        config: { accessToken, shopDomain: domain },
        error_msg: null,
        last_sync: new Date().toISOString(),
      },
      { onConflict: "branch_id,channel" }
    );

  if (error) throw error;
}

/**
 * Disconnect Shopify for a branch.
 */
export async function disconnectShopify(branchId) {
  await supabase
    .from("channel_connections")
    .upsert(
      { branch_id: branchId, channel: "shopify", status: "disconnected", config: {} },
      { onConflict: "branch_id,channel" }
    );
}

// ── API calls ─────────────────────────────────────────────────────────────

/**
 * Test that the access token + shop domain are valid by hitting /shop.json.
 */
export async function testShopifyCredentials(accessToken, shopDomain) {
  try {
    const res = await fetch(adminUrl(shopDomain, "/shop.json"), { headers: shopifyHeaders(accessToken) });
    return res.ok;
  } catch {
    return false;
  }
}

/**
 * Shopify uses cursor-based pagination (the old ?page= param is deprecated):
 * the next page's URL comes back in the Link response header, shaped like
 *   <https://shop.myshopify.com/admin/api/...&page_info=xyz>; rel="next"
 */
function nextPageUrl(linkHeader) {
  if (!linkHeader) return null;
  const part = linkHeader.split(",").find((p) => p.includes('rel="next"'));
  if (!part) return null;
  const match = part.match(/<([^>]+)>/);
  return match ? match[1] : null;
}

async function listAllShopify(shopDomain, accessToken, resource, key, extraQuery = "") {
  const all = [];
  let url = adminUrl(shopDomain, `/${resource}.json?limit=250${extraQuery}`);
  while (url) {
    let res = await fetch(url, { headers: shopifyHeaders(accessToken) });
    if (res.status === 429) {
      const wait = Number(res.headers.get("Retry-After") ?? "2") * 1000;
      await new Promise((r) => setTimeout(r, wait));
      res = await fetch(url, { headers: shopifyHeaders(accessToken) });
    }
    if (!res.ok) throw new Error(`Shopify request failed (${res.status}): ${url}`);
    const json = await res.json();
    all.push(...(json?.[key] ?? []));
    url = nextPageUrl(res.headers.get("Link"));
    if (url) await new Promise((r) => setTimeout(r, 150)); // be polite between pages
  }
  return all;
}

/** List ALL customers in the Shopify store. Raw Shopify customer objects. */
export async function listShopifyCustomers(accessToken, shopDomain) {
  return listAllShopify(shopDomain, accessToken, "customers", "customers");
}

/**
 * List ALL orders in the Shopify store (status=any — the default
 * /orders.json only returns open orders, which would miss fulfilled/
 * cancelled history).
 */
export async function listShopifyOrders(accessToken, shopDomain) {
  return listAllShopify(shopDomain, accessToken, "orders", "orders", "&status=any");
}

/** List ALL products in the Shopify catalog. Raw Shopify product objects. */
export async function listShopifyProducts(accessToken, shopDomain) {
  return listAllShopify(shopDomain, accessToken, "products", "products");
}
