/**
 * slack.js — Slack notifications for AzQueue (outbound only).
 *
 * Uses a Slack Incoming Webhook — generated by the branch owner himself in
 * his own Slack workspace — instead of a Slack App / OAuth install. Same
 * "paste a credential you generated yourself" pattern as Freshdesk/Shopify,
 * and the right tradeoff here: AzQueue only ever POSTs messages into one
 * channel, it never reads anything back from Slack, so a full Slack App
 * (OAuth, bot token, event subscriptions) would be a lot of machinery for
 * no benefit.
 *
 * HOW TO GET YOUR WEBHOOK URL:
 *   1. In Slack: go to api.slack.com/apps → "Create New App" → "From scratch"
 *      (or use the classic "Incoming WebHooks" app if your workspace has it)
 *   2. Under Features → Incoming Webhooks, switch it on
 *   3. "Add New Webhook to Workspace" → choose the channel notifications
 *      should land in → Allow
 *   4. Copy the Webhook URL (looks like https://hooks.slack.com/services/...)
 *   5. Paste it into AzQueue Settings → Integrations → Slack
 *
 * What AzQueue sends here, today:
 *   - Booking assignments: which staff member got which task, and when
 *     (Bookings.jsx, right after a booking is created with a staff member set)
 *   - WhatsApp AI handoffs: when the WhatsApp customer-service AI decides a
 *     human is needed, it posts which team should pick it up and why
 *     (wa-bot Edge Function, support_ai state)
 *
 * The webhook URL is stored in channel_connections (channel = 'slack'),
 * same RLS as every other integration — visible only to the branch owner.
 */

import { supabase } from "./supabase";

// ── Config helpers ────────────────────────────────────────────────────────

/** Load the Slack webhook URL for a branch. Returns { webhookUrl } or null. */
export async function getSlackConfig(branchId) {
  const { data } = await supabase
    .from("channel_connections")
    .select("config, status")
    .eq("branch_id", branchId)
    .eq("channel", "slack")
    .maybeSingle();

  if (!data?.config?.webhookUrl) return null;
  return { webhookUrl: data.config.webhookUrl };
}

/** Save (and test) a Slack webhook URL for a branch. Throws if invalid. */
export async function saveSlackConfig(branchId, { webhookUrl }) {
  const url = webhookUrl.trim();
  const testOk = await testSlackWebhook(url);
  if (!testOk) throw new Error("Couldn't post to that webhook URL — please check it and try again.");

  const { error } = await supabase
    .from("channel_connections")
    .upsert(
      {
        branch_id: branchId,
        channel: "slack",
        status: "connected",
        config: { webhookUrl: url },
        error_msg: null,
        last_sync: new Date().toISOString(),
      },
      { onConflict: "branch_id,channel" }
    );
  if (error) throw error;
}

/** Disconnect Slack for a branch. */
export async function disconnectSlack(branchId) {
  await supabase
    .from("channel_connections")
    .upsert(
      { branch_id: branchId, channel: "slack", status: "disconnected", config: {} },
      { onConflict: "branch_id,channel" }
    );
}

// ── Sending ──────────────────────────────────────────────────────────────

/** Post a raw test message to confirm the webhook URL actually works. */
export async function testSlackWebhook(webhookUrl) {
  try {
    const res = await fetch(webhookUrl, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ text: "✅ AzQueue is now connected to this channel." }),
    });
    return res.ok;
  } catch {
    return false;
  }
}

/**
 * Send a notification to the branch's connected Slack channel.
 * Silently no-ops if Slack isn't connected — callers don't need to check
 * first, same as how notifications.js treats missing Twilio config.
 */
export async function sendSlackNotification(branchId, text) {
  try {
    const config = await getSlackConfig(branchId);
    if (!config) return;
    await fetch(config.webhookUrl, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ text }),
    });
  } catch (e) {
    console.warn("[slack] notification failed:", e.message);
  }
}
